//
//  Quotes.swift
//  surge15
//

enum Quotes {

    // MARK: - Calendar: future day (user is looking ahead)

    static let calendarFutureDay: [String] = [
        "Woah, you're already planning your workout for this day.",
        "Love the commitment. This day isn't even here yet.",
        "Scouting out future suffering. Respect.",
        "The future you is already lacing up. Probably.",
        "Bold of you to assume you'll want to on this day.",
        "Pencil it in. Then actually show up.",
        "A blank slate. Infinite potential. No excuses yet.",
        "Future you will either thank you or blame you for this.",
        "This day is wide open. Nice.",
        "Pre-regretting skipping this one. Smart.",
        "You're thinking about the future. The future is thinking back.",
        "All that free space just waiting for a surge.",
        "Looking ahead. We love to see it.",
    ]

    // MARK: - Calendar: today with no sessions (motivating nudge)

    static let calendarToday: [String] = [
        "How about a quick run? Or 2? Or 3? Or 4?",
        "The day isn't over yet. Just saying.",
        "One lap. That's all. One tiny lap.",
        "Future you is rooting for present you. Loudly.",
        "What if you laced up right now? Wild thought.",
        "You've done harder things before breakfast.",
        "The route isn't going to run itself. Yet.",
        "A ten-minute run beats a zero-minute run every time.",
        "Go outside. Touch grass. Then run past it.",
        "You could start right now and be done before this sinks in.",
        "Not too late. Never too late. Especially not right now.",
        "One session. One decision. Let's go.",
        "Your shoes are literally right there.",
        "The only bad workout is the one that didn't happen today.",
        "You didn't come this far to skip today.",
        "The run is short. The feeling after is long.",
        "Champion energy available. Currently unclaimed.",
        "Still today. Still time. Still you.",
    ]

    // MARK: - Calendar: past day with no sessions (the roast)

    static let calendarRestDay: [String] = [
        "The couch called. You answered every time.",
        "A+ for showing up. F for moving.",
        "Rest day, or just... day?",
        "Your sneakers are collecting dust and personality.",
        "Somewhere, a treadmill is crying.",
        "The only reps today were lifting the remote.",
        "You trained hard. At doing nothing.",
        "Officially a professional rester.",
        "The gym misses you. Probably.",
        "Netflix: 1. Workout: 0.",
        "Today's workout sponsored by: the couch.",
        "You looked outside and said nope. Valid.",
        "Invisible reps. They totally count.",
        "Strong choice to do absolutely nothing.",
        "Your body is a temple. Closed today.",
        "The weights lifted themselves. You weren't there to see it.",
        "Rest is training too. ...Probably.",
        "Every champion needs a cloud watching day.",
        "You burned calories blinking. That's something.",
        "You rested so hard. Respect.",
        "Officially fueling up for next time.",
        "Today: recovery mode. From what? Unclear.",
        "The road wasn't going anywhere. You matched its energy.",
        "Legs? Never heard of them.",
        "Zero steps taken. One hundred thoughts had.",
        "You thought about working out. That's like half.",
        "The bed was too comfy. A worthy opponent.",
        "Today's pace: glacial.",
        "Warming the bench like a pro.",
        "You did nothing today with incredible commitment.",
        "Peak performance at resting.",
        "The alarm went off. You negotiated. The alarm lost.",
        "Your future self is already judging this. Lovingly.",
        "Saving energy for something important. TBD.",
        "You were in the zone. The comfort zone.",
        "Olympic-level relaxation on display here.",
        "Somewhere, a protein shake went unmade.",
        "You took the scenic route: straight to the sofa.",
        "Today was brought to you by: zero effort.",
        "You thought about lunges. That's enough.",
        "The run will still be there tomorrow. Pinky promise.",
        "Resting face AND resting legs. Synergy.",
        "Even elite athletes have days like this. Probably.",
        "Today: 0 km. Confidence: unchanged.",
        "You looked at your running shoes and said: not today, friend.",
        "A bold day to do absolutely zip.",
        "Recovery is a strategy. You're very strategic.",
        "No sessions logged. Vibe preserved.",
        "You rested like it was your job. Nailed it.",
        "The track was out there. You were in here. Balance.",
        "You gave your muscles a vacation. They send their thanks.",
        "The burpees can wait. They're very patient.",
        "Today's training log: thoughts and prayers.",
        "Technically, breathing is cardio.",
        "You were at full power the whole time. Power to relax.",
        "Your running shoes sat by the door, hopeful.",
        "You took a step back. Literally.",
        "A true rest day: no guilt, no gains, no problem.",
        "The workout planned. The day laughed.",
        "Today's miles: 0. Today's memories: unclear.",
        "The road less traveled was, in fact, not traveled.",
        "Rest hard. Play harder. Workout... eventually.",
        "Today you trained your ability to not train.",
        "A skip day is just a future motivation origin story.",
        "You rested with intention. Very zen.",
        "Legend has it they were going to work out. But first, a nap.",
    ]

    // MARK: - Calendar: surge row with no logged exercises

    static let calendarEmptySession: [String] = [
        "A+ for showing up. F for moving.",
        "Invisible reps. They totally count.",
        "Rest is training too. ...Probably.",
        "Recovery is a strategy. You're very strategic.",
        "You rested with intention. Very zen.",
        "Technically, breathing is cardio.",
        "Peak performance at resting.",
    ]

    // MARK: - Surge intent sheet

    static let surgeIntent: [String] = [
        "I see you. Putting in that work.",
        "The couch called. You didn't answer.",
        "Legs don't know it's leg day. Surprise them.",
        "You showed up. That's already 50% of it.",
        "Your future self is watching. Don't disappoint them.",
        "No one ever regretted a workout. Maybe one person...but who's counting?",
        "Sweat is just your body applauding itself.",
        "You vs. you. You're winning.",
        "The only bad workout is the one that didn't happen.",
        "The route isn't going to run itself.",
        "Your body can. Your brain is just being dramatic.",
        "Let's get this bread. And then burn it off.",
        "Today's discomfort is tomorrow's warm-up.",
        "You're here. The hard part is already done.",
        "Champions train on the days they don't want to.",
        "Pain is temporary. Screenshots of your stats are forever.",
        "Your muscles don't know it's early. Neither does your alarm. Go.",
        "Every kilometre you don't run, someone else is running it. Rude of them.",
        "Plot twist: you feel amazing after.",
        "You drove here. You might as well.",
        "Technically, blinking is cardio. But let's aim higher.",
        "Your heart wants to. Your legs will follow.",
        "You didn't come this far to only come this far.",
        "Somewhere, someone is using your motivation as their excuse not to go. Don't let them win.",
        "This is the part of the movie where you get up.",
        "Outrun your thoughts. There are a lot of them today.",
        "You've survived worse. You can survive a lap or two.",
        "Not all heroes wear capes. Some wear compression socks.",
        "The best time to work out was yesterday. The second best time is right now.",
        "One decision. One direction. One very sore tomorrow.",
        "Your body keeps the score. Make sure the score is good.",
        "Lace up. The route isn't going anywhere, but you should.",
        "You've been thinking about this all day. Now stop thinking.",
        "Discipline is just motivation with a better attendance record.",
        "Run like someone's watching. Because your future self is.",
        "The gym doesn't care about your feelings. But we do. Now go.",
        "You are one workout away from a good mood.",
        "Your legs have been waiting all day for this. They're excited. Trust them.",
        "The only person you need to be better than is last week's you.",
        "Surge. Then brunch. In that order.",
        "Go fast. Go slow. Just go.",
        "Your sneakers have been by the door all day, hopeful.",
        "The route has been patiently waiting. It's time.",
        "New body unlocked. It's on the other side of this workout.",
        "You are legally required to feel good after this. Look it up.",
        "Sometimes the hardest part is opening the app. Done. You win.",
        "Elite mindset. Amateur excuse count: zero.",
        "Later you will say: I'm glad I did that. Trust later you.",
        "You didn't skip. Iconic.",
        "Your GPS is locked. Your excuses are not.",
        "The burpees didn't do anything to you personally. Work it out.",
        "You opened the app. That's basically a workout.",
        "Science says exercise is good for you. Scientists don't skip either.",
        "Your legs: 'please no.' Your brain: 'I know.' You: starting the countdown anyway.",
        "Every step you take, every lap you make, I'll be logging it.",
        "Somewhere, a version of you who skipped is really sad right now.",
        "The only thing standing between you and done is you starting.",
        "You're not procrastinating. You're loading. Fully loaded. Let's go.",
    ]
}
